# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        egocentric: 5
        detection: 3
        annotation: 3
        domain adaptation: 3
        hand: 1
        object: 1
        interaction: 2
        video: 2
        action: 1
        dataset: 1
      
# 通知の閾値
score_threshold: 3
